import matplotlib as mpl
from matplotlib import pyplot as plt
from Bio import SeqIO
import requests
from io import StringIO as sio
from adjustText import adjust_text
import baltic as bt
import pandas as pd
import dendropy
from dendropy import Tree

# script for getting the genotypes of all background sequences, for those not present in metadata

with open('background/bg_aligned_wo_ref.fasta.treefile','r') as file:
	cts = file.read()
	tree0 = Tree.get(data=cts, schema="newick")

tree0.reroot_at_midpoint(update_bipartitions=False)
tree0.write(file=open('rerooted_wo_ref.tree', 'w'), schema="newick")
tree = bt.loadNewick('rerooted_wo_ref.tree')


# plot full background tree (no seqs generated by our project)
fig,ax = plt.subplots(figsize=(10,14),facecolor='w')

cmap=mpl.cm.cividis_r
x_attr=lambda k: k.height
tree.plotTree(ax,x_attr=x_attr,zorder=20000,linewidth=0.1)
all_ys=tree.getParameter('y')
all_xs=[tO.height for tO in tree.Objects]
all_names=[tO.name if tO.is_leaf() else '' for tO in tree.Objects]

new_xs = [all_xs[j] for j in range(len(all_xs)) if all_names[j].startswith('Consensus')]
new_ys = [all_ys[j] for j in range(len(all_xs)) if all_names[j].startswith('Consensus')]
new_names = [all_names[j] for j in range(len(all_xs)) if all_names[j].startswith('Consensus')]

# read in metadata separately 
meta = pd.read_csv('measles_bg_metadata_cleaned.csv',index_col=0)
all_clades = [meta.loc[tO.name,'clade'] if (tO.is_leaf() and tO.name in meta.index) else None for tO in tree.Objects]

all_countries = [meta.loc[tO.name,'country'] if (tO.is_leaf() and tO.name in meta.index) else None for tO in tree.Objects]
all_dates = [meta.loc[tO.name,'collection_date_iso'] if (tO.is_leaf() and tO.name in meta.index) else None for tO in tree.Objects] # Note: may want to set years to mid-year instead of first day of year 

df = pd.DataFrame([all_names, all_clades,all_xs,all_ys,all_countries],index=['name','clade','x','y','country']).T

# df = df[df['clade'].]
df = df[~df['clade'].isnull()]

df0 = df[df['name'].apply(lambda x:len(x))>0]
clades = df0.clade.unique()
for j,clade in enumerate(clades):
	df0_ = df0[df0['clade']==clade]
	ax.scatter(df0_['x'],df0_['y'],s=50,zorder=20002,label=clade,color=plt.cm.tab20b(j))

	if clade in ['B3','D8']:
		xv = df0_.x.max()
		yv = df0_.y.mean()
		ax.annotate(clade,(xv+0.001,yv),color=plt.cm.tab20b(j),fontsize=20)

ax.legend(loc='lower left')
ax.set_xlabel('Divergence',fontsize=15)
ax.grid(axis='x',ls='--',color='grey')
ax.set_yticks([])
ax.set_yticklabels([])
[ax.spines[loc].set_visible(False) for loc in ax.spines if loc in ['top','right']]
plt.savefig('measles_tree_bg.pdf')
plt.close()

### write out background seqs into corresponding files, by genotype
for clade in ['B3','D8']:
	df = meta[meta['clade']==clade]
	all_tips =[t for t in tree.Objects if t.is_leaf()]
	clade_tips = [t for t in all_tips if (t.name.split('|')[0] in df.index)]
	pNode = tree.commonAncestor(clade_tips)
	clade_subtree  = tree.subtree(starting_node=pNode)
	clade_tips_names = [t.name.split('|')[0] for t in clade_subtree.Objects if t.is_leaf()]
	original_file = 'measles_bg.fasta'
	corrected_file = f'{clade}/measles_{clade}_bg.fasta'
	with open(original_file) as original, open(corrected_file, 'w') as corrected:
		records = SeqIO.parse(original_file, 'fasta')
		for record in records:
			acc = record.id.split('|')[0]
			if acc in clade_tips_names:
				SeqIO.write(record, corrected, 'fasta')